name: GitHub-Profile-3D-Contrib

on:
  push:
    branches: [ main ]
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2

      - name: what is github.repository_owner?
        run: echo ${{ github.repository_owner }}
        
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      
      # - name: Commit & Push
      #   run: |
      #     git config user.name kjeon0901
      #     git config user.email kjeon0901@naver.com
      #     git add -A .
      #     git commit -m "generated"
      #     git push https://kjeon0901:${{ secrets.TOKEN }}@github.com/kjeon0901/kjeon0901.git main
